# Generated by Django 5.0.4 on 2024-04-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentfname', models.CharField(max_length=100)),
                ('studentlname', models.CharField(max_length=100)),
                ('studentnumber', models.IntegerField()),
                ('studentemail', models.CharField(max_length=100)),
                ('studentcourse', models.CharField(max_length=100)),
                ('studentaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
